# Generated by Django 3.1.7 on 2021-04-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('Employee_ID_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('RnD', 'Research and Development'), ('FIN', 'Finance')], max_length=10)),
                ('First_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=15)),
                ('DOB', models.DateTimeField(verbose_name='Date of Birth')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Address', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField(verbose_name='Start Date')),
                ('PreviousOccupation', models.CharField(blank=True, max_length=15, null=True)),
                ('PreviousCompany', models.CharField(blank=True, max_length=20, null=True)),
                ('Experience_in_years', models.IntegerField(default=0)),
                ('Employee_ID_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_hours_worked', models.IntegerField(default=160)),
                ('Employee_ID_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary_per_month', models.FloatField()),
                ('tax_cut_percentage', models.FloatField(default=10)),
                ('Grand_Total', models.FloatField(blank=True, null=True)),
                ('Employee_ID_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_leaves', models.IntegerField(default=2)),
                ('Employee_ID_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Phone_Number', models.IntegerField()),
                ('Personal_Phone_Number', models.IntegerField()),
                ('Landline_Number', models.IntegerField(blank=True, null=True)),
                ('Employee_ID_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_register.employeedetails')),
            ],
        ),
    ]
