# Generated by Django 3.1.7 on 2021-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='DOB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
