# Generated by Django 3.1.7 on 2021-04-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20210405_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghistory',
            name='StartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
