# Generated by Django 3.1.7 on 2021-04-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_auto_20210405_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinformation',
            name='FHI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_register.holidayinformation'),
        ),
        migrations.AddField(
            model_name='salaryinformation',
            name='FTI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_register.timeinformation'),
        ),
    ]
