# Generated by Django 3.1.7 on 2021-04-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_auto_20210407_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryinformation',
            name='FHI',
        ),
        migrations.RemoveField(
            model_name='salaryinformation',
            name='FTI',
        ),
    ]
