# Generated by Django 3.1.7 on 2021-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0005_auto_20210407_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinformation',
            name='Employee_ID_number',
        ),
        migrations.AddField(
            model_name='salaryinformation',
            name='Number_of_hours_worked',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='salaryinformation',
            name='Number_of_leaves',
            field=models.IntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='HolidayInformation',
        ),
        migrations.DeleteModel(
            name='TimeInformation',
        ),
    ]
