# Generated by Django 3.1.7 on 2021-04-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_auto_20210407_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='Company_Phone_Number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='Personal_Phone_Number',
            field=models.IntegerField(max_length=10),
        ),
    ]
