# Generated by Django 4.0.4 on 2022-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_auto_20210412_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salaryinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workinghistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
